name: jhvostov_prac_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  get_it: ^8.0.0
  cached_network_image: ^3.4.1
  go_router: ^12.1.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.0


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
